name: doctors_appointment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'



dependencies:
  cached_network_image: ^3.2.3
  bloc: ^8.1.4
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.6
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.7
  get_it: ^7.7.0
  path_provider: ^2.1.2
  flutter_svg_provider: ^1.0.7
  shared_preferences: ^2.3.2
  modal_progress_hud_nsn: ^0.5.1
  go_router: ^14.2.0
  hydrated_bloc: ^9.1.5
  sqflite: ^2.3.3+1
  dots_indicator: ^3.0.0
  intl: ^0.19.0
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.3
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4  
  uuid: ^4.5.1
  json_annotation: ^4.9.0

  font_awesome_flutter: ^10.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 
 

flutter:

  
  
  uses-material-design: true
  # To add ssss to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vector/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
